keyword_categories = {
    "I enjoy meeting new people": "Extraversion vs Introversion",
    "Crowds make me feel alive": "Extraversion vs Introversion",
    "I recharge by spending time alone": "Extraversion vs Introversion",
    "Small talk is exhausting for me": "Extraversion vs Introversion",
    "I prefer deep one-on-one conversations over large gatherings": "Extraversion vs Introversion",
    "I often seek out lively social environments": "Extraversion vs Introversion",
    "Being the center of attention excites me": "Extraversion vs Introversion",
    "I prefer listening over speaking in groups": "Extraversion vs Introversion",
    "I love being surrounded by people": "Extraversion vs Introversion",
    "I feel energized after socializing": "Extraversion vs Introversion",
    "I enjoy striking up conversations with strangers": "Extraversion vs Introversion",
    "Group activities are more fun than solitary ones for me": "Extraversion vs Introversion",
    "I feel more productive when working in a busy environment": "Extraversion vs Introversion",
    "Networking events excite me": "Extraversion vs Introversion",
    "I often initiate conversations in social settings": "Extraversion vs Introversion",
    "I enjoy being in the spotlight": "Extraversion vs Introversion",
    "I easily make new friends in unfamiliar places": "Extraversion vs Introversion",
    "I feel comfortable speaking in front of a large audience": "Extraversion vs Introversion",
    "Spending time with others helps me relieve stress": "Extraversion vs Introversion",
    "I enjoy being part of large gatherings and parties": "Extraversion vs Introversion",
    "I thrive in high-energy social settings": "Extraversion vs Introversion",
    "I often plan social events and get-togethers": "Extraversion vs Introversion",
    "I like to keep conversations going in a group": "Extraversion vs Introversion",
    "Being around others helps me think more clearly": "Extraversion vs Introversion",
    "I often feel restless when alone for long periods": "Extraversion vs Introversion",
    "I prefer fast-paced, interactive discussions": "Extraversion vs Introversion",
    "I seek excitement in social experiences": "Extraversion vs Introversion",
    "I feel drained after long social interactions": "Extraversion vs Introversion",
    "I value solitude as a way to recharge": "Extraversion vs Introversion",
    "I prefer spending time with a few close friends over a big party": "Extraversion vs Introversion",
    "I enjoy my own company and rarely feel lonely when alone": "Extraversion vs Introversion",
    "Social events can sometimes feel overwhelming": "Extraversion vs Introversion",
    "I prefer writing or texting over talking on the phone": "Extraversion vs Introversion",
    "I think before I speak rather than jumping into conversations": "Extraversion vs Introversion",
    "I enjoy quiet environments with minimal distractions": "Extraversion vs Introversion",
    "I often find myself needing breaks during social activities": "Extraversion vs Introversion",
    "I appreciate deep conversations over casual small talk": "Extraversion vs Introversion",
    "I am more reflective than expressive in social situations": "Extraversion vs Introversion",
    "I tend to observe and listen more than I speak in groups": "Extraversion vs Introversion",
    "I dislike large crowds and prefer one-on-one interactions": "Extraversion vs Introversion",
    "I enjoy hobbies that can be done alone, like reading or painting": "Extraversion vs Introversion",
    "I avoid loud and chaotic environments whenever possible": "Extraversion vs Introversion",
    "I feel most productive when working independently": "Extraversion vs Introversion",
    "I sometimes need time to process my thoughts before responding in conversations": "Extraversion vs Introversion",
    "I often prefer texting over in-person conversations": "Extraversion vs Introversion",
    "I am happiest when I have time to myself to reflect and recharge": "Extraversion vs Introversion",
    "I enjoy engaging in conversations with colleagues throughout the workday": "Extraversion vs Introversion",
    "I find it easy to start conversations with new employees": "Extraversion vs Introversion",
    "I feel energized after interacting with my coworkers": "Extraversion vs Introversion",
    "I prefer discussing ideas aloud rather than working in silence": "Extraversion vs Introversion",
    "I enjoy team meetings and brainstorming sessions": "Extraversion vs Introversion",
    "I often initiate conversations in the office and like to keep things lively": "Extraversion vs Introversion",
    "I thrive in open office environments where I can interact freely with others": "Extraversion vs Introversion",
    "I feel comfortable speaking in front of large groups or leading discussions": "Extraversion vs Introversion",
    "I enjoy networking events and actively seek new professional connections": "Extraversion vs Introversion",
    "I like exchanging ideas with colleagues rather than working in isolation": "Extraversion vs Introversion",
    "I work best in a collaborative, fast-paced environment with constant interaction": "Extraversion vs Introversion",
    "I prefer group projects over independent work": "Extraversion vs Introversion",
    "I often volunteer for team-building activities or office social events": "Extraversion vs Introversion",
    "I feel comfortable sharing my thoughts and ideas in meetings": "Extraversion vs Introversion",
    "I enjoy spontaneous discussions and impromptu brainstorming sessions": "Extraversion vs Introversion",
    "I feel motivated when surrounded by an energetic team": "Extraversion vs Introversion",
    "I actively participate in office social events and gatherings": "Extraversion vs Introversion",
    "I prefer an open-door policy where colleagues can drop by anytime": "Extraversion vs Introversion",
    "I am comfortable with making quick decisions and thinking on my feet": "Extraversion vs Introversion",
    "I naturally take charge in group discussions and projects": "Extraversion vs Introversion",
    "I enjoy mentoring new employees and helping them integrate into the team": "Extraversion vs Introversion",
    "I feel comfortable networking with senior executives and industry leaders": "Extraversion vs Introversion",
    "I actively seek leadership opportunities within my workplace": "Extraversion vs Introversion",
    "I prefer leading presentations and public speaking over working behind the scenes": "Extraversion vs Introversion",
    "I enjoy after-work gatherings and socializing with colleagues": "Extraversion vs Introversion",
    "I find it easy to balance work and social life by engaging in various activities": "Extraversion vs Introversion",
    "I prefer working in a company that encourages open communication and collaboration": "Extraversion vs Introversion",
    "I enjoy celebrating team successes with group outings or office parties": "Extraversion vs Introversion",
    "I prefer listening over speaking in group discussions": "Extraversion vs Introversion",
    "I find large meetings overwhelming and prefer one-on-one conversations": "Extraversion vs Introversion",
    "I am more comfortable communicating through emails than in-person meetings": "Extraversion vs Introversion",
    "I prefer deep, meaningful discussions over casual small talk": "Extraversion vs Introversion",
    "I need time to think before responding in meetings": "Extraversion vs Introversion",
    "I find open office spaces distracting and prefer a quiet work environment": "Extraversion vs Introversion",
    "I tend to observe discussions before sharing my thoughts": "Extraversion vs Introversion",
    "I am selective about the workplace relationships I build": "Extraversion vs Introversion",
    "I prefer having a structured schedule with minimal unexpected interruptions": "Extraversion vs Introversion",
    "I avoid office small talk and only engage in conversations when necessary": "Extraversion vs Introversion",
    "I focus best when working alone without distractions": "Extraversion vs Introversion",
    "I prefer independent tasks over collaborative group projects": "Extraversion vs Introversion",
    "I value deep concentration and uninterrupted work time": "Extraversion vs Introversion",
    "I prefer a quiet workspace where I can focus without social distractions": "Extraversion vs Introversion",
    "I work best with well-defined tasks and minimal social interaction": "Extraversion vs Introversion",
    "I often feel drained after prolonged social interactions at work": "Extraversion vs Introversion",
    "I avoid office social events and prefer spending my breaks alone": "Extraversion vs Introversion",
    "I feel more productive in a structured and solitary work environment": "Extraversion vs Introversion",
    "I prefer working remotely or in hybrid settings to reduce workplace interactions": "Extraversion vs Introversion",
    "I lead best by setting an example rather than giving direct instructions": "Extraversion vs Introversion",
    "I prefer working behind the scenes rather than being in the spotlight": "Extraversion vs Introversion",
    "I avoid workplace conflicts and prefer a peaceful work environment": "Extraversion vs Introversion",
    "I contribute through thoughtful insights rather than speaking frequently in meetings": "Extraversion vs Introversion",
    "I like planning and strategizing in advance rather than making quick decisions": "Extraversion vs Introversion",
    "I prefer work-life balance that allows me to recharge in solitude": "Extraversion vs Introversion",
    "I avoid after-work social events and prefer spending time alone or with close friends": "Extraversion vs Introversion",
    "I find networking events tiring and only attend them when necessary": "Extraversion vs Introversion",
    "I prefer spending lunch breaks alone to recharge for the rest of the day": "Extraversion vs Introversion",
    "I enjoy flexible work arrangements that allow for independent focus time": "Extraversion vs Introversion",


    "I try to see the best in others": "Agreeableness vs Antagonism",
    "Helping others gives me a sense of fulfillment": "Agreeableness vs Antagonism",
    "I avoid conflict whenever possible": "Agreeableness vs Antagonism",
    "I find it difficult to trust people completely": "Agreeableness vs Antagonism",
    "I enjoy collaborating more than competing": "Agreeableness vs Antagonism",
    "I can be skeptical of people's intentions": "Agreeableness vs Antagonism",
    "I am quick to forgive when someone apologizes": "Agreeableness vs Antagonism",
    "I sometimes doubt people's motives": "Agreeableness vs Antagonism",
    "I try to see the best in others": "Agreeableness vs Antagonism",
    "Helping others gives me a sense of fulfillment": "Agreeableness vs Antagonism",
    "I avoid conflict whenever possible": "Agreeableness vs Antagonism",
    "I find it difficult to trust people completely": "Agreeableness vs Antagonism",
    "I enjoy collaborating more than competing": "Agreeableness vs Antagonism",
    "I can be skeptical of people's intentions": "Agreeableness vs Antagonism",
    "I am quick to forgive when someone apologizes": "Agreeableness vs Antagonism",
    "I sometimes doubt people's motives": "Agreeableness vs Antagonism",
    "I tend to give people the benefit of the doubt": "Agreeableness vs Antagonism",
    "I enjoy making others feel comfortable and valued": "Agreeableness vs Antagonism",
    "I am willing to compromise to maintain harmony in relationships": "Agreeableness vs Antagonism",
    "I feel satisfied when I help someone in need": "Agreeableness vs Antagonism",
    "I avoid criticizing others unless absolutely necessary": "Agreeableness vs Antagonism",
    "I try to see situations from other people's perspectives": "Agreeableness vs Antagonism",
    "I feel uncomfortable when I see someone being treated unfairly": "Agreeableness vs Antagonism",
    "I am more likely to cooperate than to compete in most situations": "Agreeableness vs Antagonism",
    "I believe kindness should be extended to everyone, regardless of how they treat me": "Agreeableness vs Antagonism",
    "I find it easy to empathize with others' struggles": "Agreeableness vs Antagonism",
    "I value relationships over personal gain": "Agreeableness vs Antagonism",
    "I believe in giving second chances": "Agreeableness vs Antagonism",
    "I feel responsible for the well-being of those around me": "Agreeableness vs Antagonism",
    "I make an effort to be considerate of others' feelings": "Agreeableness vs Antagonism",
    "I dislike confrontation and prefer peaceful resolutions": "Agreeableness vs Antagonism",
    "I enjoy acts of generosity, even when they go unnoticed": "Agreeableness vs Antagonism",
    "I sometimes feel like people take advantage of my kindness": "Agreeableness vs Antagonism",
    "I try to remain patient even when others frustrate me": "Agreeableness vs Antagonism",
    "I am willing to help even when it inconveniences me": "Agreeableness vs Antagonism",
    "I trust people until they give me a reason not to": "Agreeableness vs Antagonism",
    "I rarely hold grudges against others": "Agreeableness vs Antagonism",
    "I feel a strong sense of duty to be there for my friends and family": "Agreeableness vs Antagonism",
    "I actively listen to my colleagues and respect their opinions": "Agreeableness vs Antagonism",
    "I make an effort to help my coworkers when they need assistance": "Agreeableness vs Antagonism",
    "I believe in teamwork and always strive to support my colleagues": "Agreeableness vs Antagonism",
    "I handle workplace disagreements with diplomacy and respect": "Agreeableness vs Antagonism",
    "I am comfortable adjusting my approach to accommodate my teammates": "Agreeableness vs Antagonism",
    "I avoid office gossip and try to maintain a positive atmosphere": "Agreeableness vs Antagonism",
    "I am willing to compromise to maintain harmony in the workplace": "Agreeableness vs Antagonism",
    "I encourage and appreciate my coworkers' contributions": "Agreeableness vs Antagonism",
    "I prioritize resolving conflicts in a calm and constructive way": "Agreeableness vs Antagonism",
    "I offer emotional support to colleagues facing workplace challenges": "Agreeableness vs Antagonism",
    "I value employees' well-being and strive to create a healthy work environment": "Agreeableness vs Antagonism",
    "I provide constructive and encouraging feedback rather than harsh criticism": "Agreeableness vs Antagonism",
    "I trust my team members and empower them to make decisions": "Agreeableness vs Antagonism",
    "I lead with empathy and consider my team's needs before making decisions": "Agreeableness vs Antagonism",
    "I celebrate the achievements of my team and acknowledge their hard work": "Agreeableness vs Antagonism",
    "I embrace a collaborative work culture and value open communication": "Agreeableness vs Antagonism",
    "I am open to different perspectives and encourage diverse viewpoints": "Agreeableness vs Antagonism",
    "I willingly share knowledge and expertise with my team": "Agreeableness vs Antagonism",
    "I treat all employees with kindness and fairness, regardless of hierarchy": "Agreeableness vs Antagonism",
    "I believe in fostering inclusivity and making everyone feel welcome at work": "Agreeableness vs Antagonism",
    "I check in on my colleagues' mental well-being and offer support if needed": "Agreeableness vs Antagonism",
    "I respect others' time and avoid disturbing them unnecessarily during work": "Agreeableness vs Antagonism",
    "I advocate for work-life balance and respect personal boundaries": "Agreeableness vs Antagonism",
    "I believe mental well-being should be prioritized in company policies": "Agreeableness vs Antagonism",
    "I believe in collaboration over competition in the workplace": "Agreeableness vs Antagonism",
    "I am willing to take on extra work to help my team succeed": "Agreeableness vs Antagonism",
    "I always acknowledge the efforts of others and give credit where it is due": "Agreeableness vs Antagonism",
    "I believe kindness and cooperation contribute to a productive work environment": "Agreeableness vs Antagonism",
    "I find it difficult to trust my colleagues and prefer working alone": "Agreeableness vs Antagonism",
    "I do not feel the need to go out of my way to help coworkers": "Agreeableness vs Antagonism",
    "I often question the competence of my colleagues": "Agreeableness vs Antagonism",
    "I believe competition in the workplace is more important than teamwork": "Agreeableness vs Antagonism",
    "I am not interested in making friends at work; it is strictly professional for me": "Agreeableness vs Antagonism",
    "I tend to be blunt and direct, even if it comes across as rude": "Agreeableness vs Antagonism",
    "I do not easily forgive colleagues who make mistakes": "Agreeableness vs Antagonism",
    "I rarely express gratitude or appreciation for my coworkers' help": "Agreeableness vs Antagonism",
    "I expect employees to follow orders without questioning my decisions": "Agreeableness vs Antagonism",
    "I am more concerned about results than how employees feel about their work": "Agreeableness vs Antagonism",
    "I find it difficult to be patient with employees who struggle with tasks": "Agreeableness vs Antagonism",
    "I am not concerned with creating a friendly work environment": "Agreeableness vs Antagonism",
    "I believe that employees should be able to handle stress on their own": "Agreeableness vs Antagonism",
    "I dislike workplace policies that promote collaboration over individual effort": "Agreeableness vs Antagonism",
    "I am not interested in participating in workplace social activities": "Agreeableness vs Antagonism",
    "I believe that hierarchy in the workplace should be strictly maintained": "Agreeableness vs Antagonism",
    "I find it annoying when colleagues ask for my help with their work": "Agreeableness vs Antagonism",
    "I do not believe mental health should be a major concern in the workplace": "Agreeableness vs Antagonism",
    "I think employees should prioritize work over personal issues": "Agreeableness vs Antagonism",
    "I do not feel obligated to support coworkers who are struggling with stress": "Agreeableness vs Antagonism",
    "I rarely care about work-life balance as long as work is getting done": "Agreeableness vs Antagonism",
    "I believe personal success is more important than team success": "Agreeableness vs Antagonism",
    "I do not enjoy collaborating with others and prefer working independently": "Agreeableness vs Antagonism",
    "I prioritize my own career growth over helping others succeed": "Agreeableness vs Antagonism",
    "I do not believe kindness is necessary for productivity in the workplace": "Agreeableness vs Antagonism",


    "I keep a detailed schedule to stay on track": "Conscientiousness vs Lack of Direction",
    "I like setting and following clear goals": "Conscientiousness vs Lack of Direction",
    "I often double-check my work to avoid mistakes": "Conscientiousness vs Lack of Direction",
    "I tend to procrastinate on important tasks": "Conscientiousness vs Lack of Direction",
    "I feel uneasy when things are unstructured": "Conscientiousness vs Lack of Direction",
    "I dislike strict schedules and prefer flexibility": "Conscientiousness vs Lack of Direction",
    "I am meticulous in my work habits": "Conscientiousness vs Lack of Direction",
    "I often start projects but struggle to finish them": "Conscientiousness vs Lack of Direction",
    "I keep a detailed schedule to stay on track": "Conscientiousness vs Lack of Direction",
    "I like setting and following clear goals": "Conscientiousness vs Lack of Direction",
    "I often double-check my work to avoid mistakes": "Conscientiousness vs Lack of Direction",
    "I tend to procrastinate on important tasks": "Conscientiousness vs Lack of Direction",
    "I feel uneasy when things are unstructured": "Conscientiousness vs Lack of Direction",
    "I dislike strict schedules and prefer flexibility": "Conscientiousness vs Lack of Direction",
    "I am meticulous in my work habits": "Conscientiousness vs Lack of Direction",
    "I often start projects but struggle to finish them": "Conscientiousness vs Lack of Direction",
    "I find it satisfying to complete tasks ahead of deadlines": "Conscientiousness vs Lack of Direction",
    "I struggle to stay focused when working on long-term goals": "Conscientiousness vs Lack of Direction",
    "I create to-do lists to organize my daily tasks": "Conscientiousness vs Lack of Direction",
    "I often put off responsibilities until the last minute": "Conscientiousness vs Lack of Direction",
    "I feel a strong need to be prepared for any situation": "Conscientiousness vs Lack of Direction",
    "I find it difficult to stick to a structured routine": "Conscientiousness vs Lack of Direction",
    "I take pride in being reliable and responsible": "Conscientiousness vs Lack of Direction",
    "I sometimes struggle with time management": "Conscientiousness vs Lack of Direction",
    "I prefer planning things out in advance rather than improvising": "Conscientiousness vs Lack of Direction",
    "I often forget deadlines or lose track of time": "Conscientiousness vs Lack of Direction",
    "I feel accomplished when I complete my tasks on time": "Conscientiousness vs Lack of Direction",
    "I work best when I have clear guidelines to follow": "Conscientiousness vs Lack of Direction",
    "I adapt easily to changes in plans or schedules": "Conscientiousness vs Lack of Direction",
    "I have a hard time keeping my workspace organized": "Conscientiousness vs Lack of Direction",
    "I follow through on my commitments even when it's inconvenient": "Conscientiousness vs Lack of Direction",
    "I tend to be spontaneous rather than sticking to plans": "Conscientiousness vs Lack of Direction",
    "I feel overwhelmed when I have too many tasks to complete": "Conscientiousness vs Lack of Direction",
    "I prefer a flexible schedule over a rigid routine": "Conscientiousness vs Lack of Direction",
    "I always set deadlines for myself to stay productive": "Conscientiousness vs Lack of Direction",
    "I struggle with self-discipline when working independently": "Conscientiousness vs Lack of Direction",
    "I enjoy setting ambitious goals and working towards them": "Conscientiousness vs Lack of Direction",
    "I feel frustrated when others are disorganized": "Conscientiousness vs Lack of Direction",
    "I tend to lose interest in projects before they are completed": "Conscientiousness vs Lack of Direction",
    "I prefer to take my time and do things carefully rather than rushing": "Conscientiousness vs Lack of Direction",
    "I feel more productive when I have a structured daily routine": "Conscientiousness vs Lack of Direction",
    "I often find myself making last-minute changes to my plans": "Conscientiousness vs Lack of Direction",
    "I always plan my work schedule in advance to meet deadlines": "Conscientiousness vs Lack of Direction",
    "I take pride in completing tasks efficiently and on time": "Conscientiousness vs Lack of Direction",
    "I prefer structured workflows and detailed planning over spontaneous tasks": "Conscientiousness vs Lack of Direction",
    "I make to-do lists and track my progress to stay organized": "Conscientiousness vs Lack of Direction",
    "I feel responsible for ensuring high-quality results in my work": "Conscientiousness vs Lack of Direction",
    "I am meticulous in reviewing my work to avoid errors": "Conscientiousness vs Lack of Direction",
    "I set clear long-term career goals and work towards achieving them": "Conscientiousness vs Lack of Direction",
    "I prefer finishing one task before starting another to maintain focus": "Conscientiousness vs Lack of Direction",
    "I keep my workspace clean and well-organized to improve productivity": "Conscientiousness vs Lack of Direction",
    "I always double-check my work before submitting it": "Conscientiousness vs Lack of Direction",
    "I am proactive in identifying and solving problems before they escalate": "Conscientiousness vs Lack of Direction",
    "I manage my time effectively and rarely miss deadlines": "Conscientiousness vs Lack of Direction",
    "I take responsibility for my mistakes and work on improving them": "Conscientiousness vs Lack of Direction",
    "I prefer working in a structured environment with clear expectations": "Conscientiousness vs Lack of Direction",
    "I follow company policies and procedures carefully": "Conscientiousness vs Lack of Direction",
    "I take initiative in organizing and leading projects when needed": "Conscientiousness vs Lack of Direction",
    "I always prioritize my tasks based on urgency and importance": "Conscientiousness vs Lack of Direction",
    "I believe attention to detail is crucial for success in any role": "Conscientiousness vs Lack of Direction",
    "I set personal performance benchmarks and strive to meet them": "Conscientiousness vs Lack of Direction",
    "I am consistent in delivering high-quality work regardless of circumstances": "Conscientiousness vs Lack of Direction",
    "I struggle with keeping track of deadlines and often submit work late": "Conscientiousness vs Lack of Direction",
    "I find it difficult to follow a structured schedule or routine": "Conscientiousness vs Lack of Direction",
    "I often start multiple tasks but have trouble completing them": "Conscientiousness vs Lack of Direction",
    "I do not put much effort into organizing my work environment": "Conscientiousness vs Lack of Direction",
    "I tend to leave tasks unfinished and move on to other things": "Conscientiousness vs Lack of Direction",
    "I rarely plan my work in advance and prefer to do things last minute": "Conscientiousness vs Lack of Direction",
    "I often forget important meetings or assignments": "Conscientiousness vs Lack of Direction",
    "I do not enjoy setting long-term career or work goals": "Conscientiousness vs Lack of Direction",
    "I tend to procrastinate and delay important tasks": "Conscientiousness vs Lack of Direction",
    "I struggle with maintaining focus and frequently get distracted": "Conscientiousness vs Lack of Direction",
    "I do not see the point in being too detail-oriented with work tasks": "Conscientiousness vs Lack of Direction",
    "I get overwhelmed by large projects and avoid them until the last minute": "Conscientiousness vs Lack of Direction",
    "I rarely review my work for errors before submitting it": "Conscientiousness vs Lack of Direction",
    "I find it difficult to stay motivated for long periods": "Conscientiousness vs Lack of Direction",
    "I do not have a fixed daily routine and prefer to go with the flow": "Conscientiousness vs Lack of Direction",
    "I often rely on others to remind me of deadlines and responsibilities": "Conscientiousness vs Lack of Direction",
    "I avoid taking on leadership roles because they require too much responsibility": "Conscientiousness vs Lack of Direction",
    "I struggle with prioritizing tasks and often work on low-priority things first": "Conscientiousness vs Lack of Direction",
    "I prefer working in an unstructured environment without strict deadlines": "Conscientiousness vs Lack of Direction",
    "I do not feel the need to stick to company policies and procedures strictly": "Conscientiousness vs Lack of Direction",



    "I often feel overwhelmed when faced with tight deadlines": "Neuroticism vs Emotional Stability",
    "I frequently worry about making mistakes at work": "Neuroticism vs Emotional Stability",
    "I tend to overthink my work decisions and second-guess myself": "Neuroticism vs Emotional Stability",
    "I find it difficult to stay calm during high-pressure situations": "Neuroticism vs Emotional Stability",
    "I get stressed easily when multiple tasks pile up": "Neuroticism vs Emotional Stability",
    "I often take workplace criticism personally": "Neuroticism vs Emotional Stability",
    "I struggle to maintain focus when I am anxious about my performance": "Neuroticism vs Emotional Stability",
    "I feel insecure about my job stability even when I perform well": "Neuroticism vs Emotional Stability",
    "I get frustrated easily when unexpected problems arise at work": "Neuroticism vs Emotional Stability",
    "I find it hard to disconnect from work stress even after office hours": "Neuroticism vs Emotional Stability",
    "I frequently compare my performance to others and feel inadequate": "Neuroticism vs Emotional Stability",
    "I often feel emotionally drained after a long workday": "Neuroticism vs Emotional Stability",
    "I am easily discouraged when a project does not go as planned": "Neuroticism vs Emotional Stability",
    "I tend to focus more on negative feedback than positive recognition": "Neuroticism vs Emotional Stability",
    "I find it difficult to handle uncertainty in the workplace": "Neuroticism vs Emotional Stability",
    "I feel uneasy when I don't receive immediate responses from my manager": "Neuroticism vs Emotional Stability",
    "I sometimes fear asking questions in meetings because I might sound incompetent": "Neuroticism vs Emotional Stability",
    "I replay past work mistakes in my mind and dwell on them": "Neuroticism vs Emotional Stability",
    "I experience mood swings depending on how my workday goes": "Neuroticism vs Emotional Stability",
    "I tend to procrastinate because of workplace anxiety": "Neuroticism vs Emotional Stability",
    "I remain calm and composed under work pressure": "Neuroticism vs Emotional Stability",
    "I handle workplace stress in a balanced and constructive way": "Neuroticism vs Emotional Stability",
    "I see workplace challenges as opportunities to grow rather than sources of stress": "Neuroticism vs Emotional Stability",
    "I can separate my emotions from professional decision-making": "Neuroticism vs Emotional Stability",
    "I stay focused and productive even in high-stress situations": "Neuroticism vs Emotional Stability",
    "I handle negative feedback professionally without taking it personally": "Neuroticism vs Emotional Stability",
    "I adapt well to unexpected workplace changes without feeling anxious": "Neuroticism vs Emotional Stability",
    "I do not let minor workplace conflicts affect my mood or productivity": "Neuroticism vs Emotional Stability",
    "I maintain a positive outlook even when projects do not go as planned": "Neuroticism vs Emotional Stability",
    "I am confident in my abilities and do not constantly seek reassurance": "Neuroticism vs Emotional Stability",
    "I can disconnect from work stress and relax during my free time": "Neuroticism vs Emotional Stability",
    "I approach workplace setbacks with a problem-solving mindset rather than frustration": "Neuroticism vs Emotional Stability",
    "I do not let job uncertainty negatively affect my performance": "Neuroticism vs Emotional Stability",
    "I am comfortable asking for help or clarification without feeling self-conscious": "Neuroticism vs Emotional Stability",
    "I am not easily discouraged by workplace criticism or setbacks": "Neuroticism vs Emotional Stability",
    "I maintain steady energy levels throughout my workday without emotional exhaustion": "Neuroticism vs Emotional Stability",
    "I can handle difficult conversations with colleagues professionally and calmly": "Neuroticism vs Emotional Stability",
    "I do not dwell on past work mistakes and prefer to focus on improvement": "Neuroticism vs Emotional Stability",
    "I remain composed even in unpredictable or high-pressure work environments": "Neuroticism vs Emotional Stability",
    "I have a healthy work-life balance and do not let work stress dominate my personal life": "Neuroticism vs Emotional Stability",
    

    "I enjoy exploring new cultures and ideas": "Openness vs Closeness",
    "I often seek out new artistic experiences": "Openness vs Closeness",
    "I enjoy abstract and philosophical discussions": "Openness vs Closeness",
    "I feel more comfortable with familiar routines": "Openness vs Closeness",
    "I prefer facts and logic over abstract thinking": "Openness vs Closeness",
    "I embrace change and innovation": "Openness vs Closeness",
    "I have a vivid imagination and love to daydream": "Openness vs Closeness",
    "I find comfort in traditional ways of doing things": "Openness vs Closeness",
    "I enjoy brainstorming new ideas to improve our workflow": "Openness vs Closeness",
    "I am eager to experiment with different ways of doing tasks": "Openness vs Closeness",
    "I welcome changes in company policies and see them as opportunities": "Openness vs Closeness",
    "I actively seek professional development opportunities to learn new skills": "Openness vs Closeness",
    "I am comfortable working in a fast-paced and unpredictable environment": "Openness vs Closeness",
    "I enjoy collaborating with diverse teams and learning from different perspectives": "Openness vs Closeness",
    "I am always looking for ways to innovate and improve existing processes": "Openness vs Closeness",
    "I believe that embracing technology is crucial for staying competitive": "Openness vs Closeness",
    "I like taking on new challenges that push me out of my comfort zone": "Openness vs Closeness",
    "I thrive in environments where I can think outside the box": "Openness vs Closeness",
    "I adapt quickly to shifting priorities and unexpected changes at work": "Openness vs Closeness",
    "I enjoy attending industry conferences and networking with new professionals": "Openness vs Closeness",
    "I am comfortable voicing unconventional ideas in meetings": "Openness vs Closeness",
    "I believe that flexible work arrangements boost creativity and productivity": "Openness vs Closeness",
    "I am excited about working with international teams and experiencing different work cultures": "Openness vs Closeness",
    "I see mistakes as learning opportunities rather than failures": "Openness vs Closeness",
    "I enjoy working in dynamic industries where trends evolve rapidly": "Openness vs Closeness",
    "I prefer roles that allow me to explore and experiment with new strategies": "Openness vs Closeness",
    "I see feedback as a valuable tool for growth, even when it's critical": "Openness vs Closeness",
    "I appreciate a workplace that encourages innovation and risk-taking": "Openness vs Closeness",
    "I feel most productive when I follow a consistent daily routine at work": "Openness vs Closeness",
    "I prefer clearly defined job roles and responsibilities": "Openness vs Closeness",
    "I feel uncomfortable when company policies or procedures change frequently": "Openness vs Closeness",
    "I prefer using well-established methods rather than experimenting with new ones": "Openness vs Closeness",
    "I find comfort in working with familiar colleagues and teams": "Openness vs Closeness",
    "I believe that sticking to proven strategies is better than taking unnecessary risks": "Openness vs Closeness",
    "I prefer a structured and hierarchical work environment over a flexible one": "Openness vs Closeness",
    "I find rapid changes in company direction unsettling": "Openness vs Closeness",
    "I work best when I have a clear set of instructions and guidelines": "Openness vs Closeness",
    "I prefer traditional office setups over remote or hybrid work arrangements": "Openness vs Closeness",
    "I appreciate strict deadlines and predefined schedules": "Openness vs Closeness",
    "I value long-term stability in my job more than frequent career shifts": "Openness vs Closeness",
    "I am skeptical of new workplace trends until they have been widely tested": "Openness vs Closeness",
    "I feel more secure in companies with long-standing traditions and values": "Openness vs Closeness",
    "I prefer to work in industries that are predictable rather than disruptive": "Openness vs Closeness",
    "I tend to resist major shifts in company culture or management style": "Openness vs Closeness",
    "I find innovation initiatives overwhelming and unnecessary at times": "Openness vs Closeness",
    "I would rather master one skill deeply than learn multiple new skills": "Openness vs Closeness",
    "I feel most comfortable when my work tasks remain consistent over time": "Openness vs Closeness",
    "I prefer following established career paths rather than taking uncertain opportunities": "Openness vs Closeness",
}